/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface VaultV2Interface extends utils.Interface {
  functions: {
    "claimGrant(uint256)": FunctionFragment;
    "createGrant(address,string,string,address)": FunctionFragment;
    "currentGrantId()": FunctionFragment;
    "fundGrant(uint256,uint256)": FunctionFragment;
    "funders(uint256,address)": FunctionFragment;
    "grants(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "withdrawGrant(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "claimGrant"
      | "createGrant"
      | "currentGrantId"
      | "fundGrant"
      | "funders"
      | "grants"
      | "owner"
      | "withdrawGrant"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimGrant",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createGrant",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "currentGrantId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundGrant",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "funders",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "grants",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawGrant",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "claimGrant", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentGrantId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundGrant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "funders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grants", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawGrant",
    data: BytesLike
  ): Result;

  events: {
    "Claim(uint256,address,uint256,address)": EventFragment;
    "Creation(uint256,string,string,address,address,uint256,uint256)": EventFragment;
    "Fund(uint256,address,uint256,address)": EventFragment;
    "Withdraw(uint256,address,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Creation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Fund"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export interface ClaimEventObject {
  grantId: BigNumber;
  token: string;
  amount: BigNumber;
  recipient: string;
}
export type ClaimEvent = TypedEvent<
  [BigNumber, string, BigNumber, string],
  ClaimEventObject
>;

export type ClaimEventFilter = TypedEventFilter<ClaimEvent>;

export interface CreationEventObject {
  id: BigNumber;
  name: string;
  purpose: string;
  token: string;
  recipient: string;
  start: BigNumber;
  end: BigNumber;
}
export type CreationEvent = TypedEvent<
  [BigNumber, string, string, string, string, BigNumber, BigNumber],
  CreationEventObject
>;

export type CreationEventFilter = TypedEventFilter<CreationEvent>;

export interface FundEventObject {
  id: BigNumber;
  token: string;
  amount: BigNumber;
  user: string;
}
export type FundEvent = TypedEvent<
  [BigNumber, string, BigNumber, string],
  FundEventObject
>;

export type FundEventFilter = TypedEventFilter<FundEvent>;

export interface WithdrawEventObject {
  id: BigNumber;
  token: string;
  amount: BigNumber;
  user: string;
}
export type WithdrawEvent = TypedEvent<
  [BigNumber, string, BigNumber, string],
  WithdrawEventObject
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface VaultV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VaultV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claimGrant(
      grantId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createGrant(
      token: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      purpose: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentGrantId(overrides?: CallOverrides): Promise<[BigNumber]>;

    fundGrant(
      grantId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    funders(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    grants(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber
      ] & {
        id: BigNumber;
        name: string;
        purpose: string;
        token: string;
        amount: BigNumber;
        recipient: string;
        start: BigNumber;
        end: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    withdrawGrant(
      grantId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  claimGrant(
    grantId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createGrant(
    token: PromiseOrValue<string>,
    name: PromiseOrValue<string>,
    purpose: PromiseOrValue<string>,
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentGrantId(overrides?: CallOverrides): Promise<BigNumber>;

  fundGrant(
    grantId: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  funders(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  grants(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber
    ] & {
      id: BigNumber;
      name: string;
      purpose: string;
      token: string;
      amount: BigNumber;
      recipient: string;
      start: BigNumber;
      end: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  withdrawGrant(
    grantId: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claimGrant(
      grantId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    createGrant(
      token: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      purpose: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    currentGrantId(overrides?: CallOverrides): Promise<BigNumber>;

    fundGrant(
      grantId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    funders(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grants(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber
      ] & {
        id: BigNumber;
        name: string;
        purpose: string;
        token: string;
        amount: BigNumber;
        recipient: string;
        start: BigNumber;
        end: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    withdrawGrant(
      grantId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "Claim(uint256,address,uint256,address)"(
      grantId?: null,
      token?: null,
      amount?: null,
      recipient?: null
    ): ClaimEventFilter;
    Claim(
      grantId?: null,
      token?: null,
      amount?: null,
      recipient?: null
    ): ClaimEventFilter;

    "Creation(uint256,string,string,address,address,uint256,uint256)"(
      id?: null,
      name?: null,
      purpose?: null,
      token?: null,
      recipient?: null,
      start?: null,
      end?: null
    ): CreationEventFilter;
    Creation(
      id?: null,
      name?: null,
      purpose?: null,
      token?: null,
      recipient?: null,
      start?: null,
      end?: null
    ): CreationEventFilter;

    "Fund(uint256,address,uint256,address)"(
      id?: null,
      token?: null,
      amount?: null,
      user?: null
    ): FundEventFilter;
    Fund(id?: null, token?: null, amount?: null, user?: null): FundEventFilter;

    "Withdraw(uint256,address,uint256,address)"(
      id?: null,
      token?: null,
      amount?: null,
      user?: null
    ): WithdrawEventFilter;
    Withdraw(
      id?: null,
      token?: null,
      amount?: null,
      user?: null
    ): WithdrawEventFilter;
  };

  estimateGas: {
    claimGrant(
      grantId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createGrant(
      token: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      purpose: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentGrantId(overrides?: CallOverrides): Promise<BigNumber>;

    fundGrant(
      grantId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    funders(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grants(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawGrant(
      grantId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimGrant(
      grantId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createGrant(
      token: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      purpose: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentGrantId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fundGrant(
      grantId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    funders(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grants(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawGrant(
      grantId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
